// Seeded mock data used by the in-memory Supabase mock client.
// Keep shapes loose; pages tend to destructure defensively.

const now = new Date().toISOString()
const daysAgo = (n: number) => new Date(Date.now() - n * 86400000).toISOString()

export const demoJobs = [
  {
    id: "job-1",
    title: "Senior Frontend Developer",
    description: "Build modern React applications for our growing platform. Experience with Next.js, TypeScript, and Tailwind required.",
    company: "TechCorp Tacurong",
    location: "Tacurong City",
    employment_type: "Full-time",
    salary_min: 45000,
    salary_max: 70000,
    salary_period: "monthly",
    status: "active",
    employer_id: "demo-employer-1",
    created_at: daysAgo(2),
    published_at: daysAgo(2),
    updated_at: daysAgo(1),
    skills_required: ["React", "TypeScript", "Tailwind CSS", "Next.js"],
    experience_level: "Senior",
    education_required: "Bachelor's",
    applications_count: 12,
  },
  {
    id: "job-2",
    title: "Tuna Processing Operator",
    description: "Operate machinery in tuna canning line. Training provided.",
    company: "Tacurong Seafoods",
    location: "Tacurong City",
    employment_type: "Full-time",
    salary_min: 18000,
    salary_max: 25000,
    salary_period: "monthly",
    status: "active",
    employer_id: "demo-employer-2",
    created_at: daysAgo(5),
    published_at: daysAgo(5),
    updated_at: daysAgo(3),
    skills_required: ["Manufacturing", "Quality Control"],
    experience_level: "Entry",
    education_required: "High School",
    applications_count: 34,
  },
  {
    id: "job-3",
    title: "BPO Customer Service Representative",
    description: "Handle inbound customer support calls for US-based clients. Night shift.",
    company: "ConnectBPO",
    location: "Tacurong City",
    employment_type: "Full-time",
    salary_min: 22000,
    salary_max: 32000,
    salary_period: "monthly",
    status: "active",
    employer_id: "demo-employer-3",
    created_at: daysAgo(7),
    published_at: daysAgo(7),
    updated_at: daysAgo(6),
    skills_required: ["Customer Service", "English Proficiency"],
    experience_level: "Entry",
    education_required: "Some College",
    applications_count: 56,
  },
  {
    id: "job-4",
    title: "Civil Engineer",
    description: "Lead infrastructure projects for SOCCSKSARGEN region.",
    company: "Mindanao Builders Inc.",
    location: "Tacurong City",
    employment_type: "Full-time",
    salary_min: 50000,
    salary_max: 85000,
    salary_period: "monthly",
    status: "active",
    employer_id: "demo-employer-4",
    created_at: daysAgo(10),
    published_at: daysAgo(10),
    updated_at: daysAgo(8),
    skills_required: ["AutoCAD", "Project Management", "PRC License"],
    experience_level: "Mid",
    education_required: "Bachelor's",
    applications_count: 8,
  },
]

export const demoEmployers = [
  {
    id: "demo-employer-1",
    company_name: "TechCorp Tacurong",
    industry: "Information Technology",
    company_size: "51-200",
    address: "Pioneer Ave, Tacurong City",
    website: "https://techcorp.example.ph",
    description: "Leading software company in SOCCSKSARGEN.",
    status: "approved",
    is_approved: true,
    approved_at: daysAgo(30),
    created_at: daysAgo(60),
    contact_person: "Maria Cruz",
    contact_email: "hr@techcorp.example.ph",
    contact_phone: "+63 917 123 4567",
    logo_url: null,
  },
  {
    id: "demo-employer-2",
    company_name: "Tacurong Seafoods",
    industry: "Food & Beverage Manufacturing",
    company_size: "501-1000",
    address: "Fishport Complex, Tacurong City",
    website: "https://tacurongseafoods.example.ph",
    description: "Leading tuna canning and processing company.",
    status: "approved",
    is_approved: true,
    approved_at: daysAgo(90),
    created_at: daysAgo(120),
    contact_person: "Jose Reyes",
    contact_email: "careers@tacurongseafoods.example.ph",
    contact_phone: "+63 917 234 5678",
    logo_url: null,
  },
  {
    id: "demo-employer-3",
    company_name: "ConnectBPO",
    industry: "Business Process Outsourcing",
    company_size: "201-500",
    address: "KCC Mall, Tacurong City",
    website: "https://connectbpo.example.ph",
    description: "24/7 customer service operations.",
    status: "approved",
    is_approved: true,
    approved_at: daysAgo(45),
    created_at: daysAgo(80),
    contact_person: "Anna Lim",
    contact_email: "recruiting@connectbpo.example.ph",
    contact_phone: "+63 917 345 6789",
    logo_url: null,
  },
  {
    id: "demo-employer-pending-1",
    company_name: "NewVenture Logistics",
    industry: "Logistics",
    company_size: "11-50",
    address: "Santiago Blvd, Tacurong City",
    website: null,
    description: "Last-mile delivery startup.",
    status: "pending",
    is_approved: false,
    approved_at: null,
    created_at: daysAgo(3),
    contact_person: "Pedro Dela Cruz",
    contact_email: "pedro@newventure.example.ph",
    contact_phone: "+63 917 456 7890",
    logo_url: null,
  },
]

export const demoJobseekers = [
  {
    id: "demo-jobseeker-1",
    first_name: "Juan",
    last_name: "Santos",
    email: "jobseeker@demo.local",
    phone: "+63 917 555 1111",
    nsrp_id: "NSRP-2026-0001",
    address: "Buenaflor, Tacurong City",
    birth_date: "1995-06-15",
    gender: "male",
    civil_status: "single",
    summary: "Frontend developer with 5 years of experience.",
    profile_image_url: null,
    skills: ["React", "TypeScript", "Tailwind CSS", "Node.js"],
    desired_position: "Senior Frontend Developer",
    desired_salary: 60000,
    status: "active",
    created_at: daysAgo(45),
  },
  {
    id: "demo-jobseeker-2",
    first_name: "Maria",
    last_name: "Garcia",
    email: "maria.garcia@demo.local",
    phone: "+63 917 555 2222",
    nsrp_id: "NSRP-2026-0002",
    address: "Tina, Tacurong City",
    birth_date: "1998-03-22",
    gender: "female",
    civil_status: "single",
    summary: "Recent graduate looking for entry-level roles.",
    profile_image_url: null,
    skills: ["Customer Service", "English", "MS Office"],
    desired_position: "Customer Service Representative",
    desired_salary: 25000,
    status: "active",
    created_at: daysAgo(20),
  },
]

export const demoApplications = [
  {
    id: "app-1",
    job_id: "job-1",
    jobseeker_id: "demo-jobseeker-1",
    employer_id: "demo-employer-1",
    status: "under_review",
    applied_at: daysAgo(3),
    cover_letter: "Excited to apply for this role.",
    match_score: 87,
    created_at: daysAgo(3),
  },
  {
    id: "app-2",
    job_id: "job-3",
    jobseeker_id: "demo-jobseeker-2",
    employer_id: "demo-employer-3",
    status: "submitted",
    applied_at: daysAgo(1),
    cover_letter: "I'd love to join your team.",
    match_score: 72,
    created_at: daysAgo(1),
  },
  {
    id: "app-3",
    job_id: "job-2",
    jobseeker_id: "demo-jobseeker-1",
    employer_id: "demo-employer-2",
    status: "rejected",
    applied_at: daysAgo(15),
    cover_letter: "Interested in this opportunity.",
    match_score: 45,
    created_at: daysAgo(15),
  },
]

export const demoNotifications = [
  { id: "n1", user_id: "demo-jobseeker-1", title: "Application status updated", message: "Your application for Senior Frontend Developer is now under review.", read: false, created_at: daysAgo(1), type: "application" },
  { id: "n2", user_id: "demo-jobseeker-1", title: "New matching job", message: "We found 3 new jobs that match your profile.", read: false, created_at: daysAgo(2), type: "match" },
  { id: "n3", user_id: "demo-employer-1", title: "New applicant", message: "Juan Santos applied to Senior Frontend Developer.", read: true, created_at: daysAgo(3), type: "application" },
  { id: "n4", user_id: "demo-admin-1", title: "Employer awaiting approval", message: "NewVenture Logistics is pending verification.", read: false, created_at: daysAgo(3), type: "approval" },
]

export const demoMessages = [
  { id: "m1", sender_id: "demo-employer-1", recipient_id: "demo-jobseeker-1", content: "Thanks for applying. Are you available for an interview Thursday?", created_at: daysAgo(1), read: false },
  { id: "m2", sender_id: "demo-jobseeker-1", recipient_id: "demo-employer-1", content: "Yes, Thursday works. What time?", created_at: daysAgo(1), read: true },
]

export const demoReferralSlips = [
  { id: "rs1", slip_number: "RS-2026-0001", jobseeker_id: "demo-jobseeker-1", job_id: "job-1", employer_id: "demo-employer-1", status: "issued", issued_at: daysAgo(3), qr_code_url: null, created_at: daysAgo(3) },
]

export const demoAuditLogs = [
  { id: "al1", action: "user.login", actor_id: "demo-admin-1", target_id: null, metadata: {}, created_at: daysAgo(1) },
  { id: "al2", action: "employer.approved", actor_id: "demo-admin-1", target_id: "demo-employer-1", metadata: { company_name: "TechCorp Tacurong" }, created_at: daysAgo(30) },
]

export const demoAccessRequests = [
  { id: "ar1", requester_email: "newadmin@example.ph", requester_name: "Carlos Reyes", reason: "TaraCurong staff requesting admin access", status: "pending", created_at: daysAgo(2) },
]

export const demoAdmins = [
  { id: "demo-admin-1", email: "admin@demo.local", first_name: "Demo", last_name: "Admin", role: "admin", status: "active", created_at: daysAgo(180) },
]

// Lookup keyed by table name. Pages query a wide variety of tables;
// unknown ones fall back to an empty array.
export const TABLE_DATA: Record<string, any[]> = {
  jobs: demoJobs,
  employers: demoEmployers,
  jobseekers: demoJobseekers,
  applications: demoApplications,
  notifications: demoNotifications,
  messages: demoMessages,
  referral_slips: demoReferralSlips,
  audit_logs: demoAuditLogs,
  access_requests: demoAccessRequests,
  admins: demoAdmins,
  users: [
    ...demoAdmins.map(a => ({ id: a.id, email: a.email, role: "admin", first_name: a.first_name, last_name: a.last_name })),
    ...demoEmployers.map(e => ({ id: e.id, email: e.contact_email, role: "employer", company_name: e.company_name })),
    ...demoJobseekers.map(j => ({ id: j.id, email: j.email, role: "jobseeker", first_name: j.first_name, last_name: j.last_name })),
  ],
  jobseeker_education: [],
  jobseeker_experience: [],
  jobseeker_trainings: [],
  jobseeker_licenses: [],
  jobseeker_languages: [],
  job_match_scores: demoApplications.map(a => ({ job_id: a.job_id, jobseeker_id: a.jobseeker_id, score: a.match_score, percentile_rank: 0.75, score_version: "1.0.0", created_at: a.created_at })),
  saved_jobs: [{ id: "sj1", jobseeker_id: "demo-jobseeker-1", job_id: "job-4", created_at: daysAgo(2) }],
  feedback_logs: [],
  ai_matching_logs: [],
  settings: [{ key: "site_name", value: "TaraCurong" }],
  experience_highlights: [],
  video_content: [],
}

export const getTableRows = (table: string): any[] => TABLE_DATA[table] ?? []
